name: Novo requisito
title: FED - <breve descrição do requisito>
description: "Requisito a ser implementado (Feature, História de usuário)"
labels: ["feature"]
projects: ["Salgado2004/projects/3"]
body:
  - type: markdown
    attributes:
      value: "## Os requisitos são as atividades semanais de cada integrante da equipe"
  - type: input
    attributes:
      label: Sendo
      description: Quem se beneficia do requisito
      placeholder: um cliente, um funcionário, etc...
    validations:
      required: true
  - type: input
    attributes:
      label: Quero
      description: Objetivo do requisito
      placeholder: acessar meu perfil, visualizar um serviço, etc...
    validations:
      required: true
  - type: input
    attributes:
      label: Para
      description: Resultado do requisito
      placeholder: organizar minhas informações, gerenciar o andamento, etc...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "O que deve ser feito (use o formato de lista do markdown iniciando cada linha com -)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Notas"
      description: "Outras informações úteis, regras de negócio, requisitos relacionados, links para a wiki, etc."
